# Travis configuration file
---
dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    directories:
        - $HOME/data/download/
        - $HOME/miniconda3/

before_install:
    - bash .travis/travis_before_install.sh
    - export PATH="/home/travis/miniconda3/bin:$PATH"

install:
    - export PATH="/home/travis/miniconda3/bin:$PATH"
    - conda config --add channels defaults
    - conda config --add channels conda-forge
    - conda config --add channels bioconda
    - conda install --yes -c bioconda snakemake=5.1.5
    - bash src/install/from_tarball.sh
    - snakemake --use-conda --create-envs-only
    - conda clean --all --yes

script:
    - export PATH="/home/travis/miniconda3/bin:$PATH"
    - snakemake --timestamp --resources memory_gb=3 --use-conda -j

after_failure:
