samples:
    pop1:
        min_count: "2"
        pool_size: "500"
        min_coverage: "5"
        max_coverage: "200"
        target_coverage: "10"
        libraries:
            lib1:
                forward: data/reads/pop1_1.fq.gz
                reverse: data/reads/pop1_2.fq.gz
                adaptor: data/adapters/TruSeq3-PE-2.fa
                phred:   phred33
            # lib2:
            #     forward: data/reads/pop1_1.fastq.gz
            #     reverse: data/reads/pop1_2.fastq.gz
            #     adaptor: data/adapters/TruSeq3-PE-2.fa
            #     phred:   phred33
    pop2:
        min_count: "2"
        pool_size: "500"
        min_coverage: "5"
        max_coverage: "200"
        target_coverage: "10"
        libraries:
            lib1:
                forward: data/reads/pop2_1.fq.gz
                reverse: data/reads/pop2_2.fq.gz
                adaptor: data/adapters/TruSeq3-PE-2.fa
                phred:   phred33

reference:
    dna: data/genome/2R.fa.gz

chromosomes:
    2R

trimmomatic_params:
    "AVGQUAL:3 MINLEN:31 LEADING:19 TRAILING:19 MINLEN:31 SLIDINGWINDOW:4:5 LEADING:5 TRAILING:5 MINLEN:25 TOPHRED33"

bwa_params:
    threads: 2  # If you have lots of libraries, keep it to two, if you have < 10, raise it. samtools sort is the bottleneck
    additional_params: ""

picard_markduplicates_params:
    memory_gb: 1

popoolation_params:
    find_indels:
        indel_window:       5
        min_count:          2
    subsample:
        min_qual:            20
        method:             withoutreplace
        target_coverage:     10
    D:
        min_coverage: 4
        min_count:           2
        min_covered_fraction: 0.5
        step_size:           1000
        window_size:         1000
    pi:
        min_coverage: 4
        min_count:           2
        min_covered_fraction: 0.5
        step_size:           1000
        window_size:         1000
    theta:
        min_coverage: 4
        min_count:           2
        min_covered_fraction: 0.5
        step_size:           1000
        window_size:         1000

popoolation2_params:
    mpileup2sync:
        min_qual:  20
        memory_gb: 2
    find_indels:
        indel_window: 5
        min_count: 20
    subsample_synchronized:
        target_coverage: 10
        max_coverage:    10000
        method:          withoutreplace
    fst_sliding:
        window_size:          1
        step_size:            1
        min_covered_fraction: 1.0
        min_coverage:         4
        max_coverage:         120
        min_count:            3
