# Execution params
---

trimmomatic:
    extra: >
        AVGQUAL:3
        MINLEN:31
        LEADING:19
        TRAILING:19
        MINLEN:31
        SLIDINGWINDOW:4:5
        LEADING:5
        TRAILING:5
        MINLEN:25
        TOPHRED33


# If you have lots of libraries, keep the number of threads to two,
# if you have < 10, raise it. samtools sort is the bottleneck
bwa:
    threads: 2
    extra: ""

picard_markduplicates:
    memory_gb: 1

popoolation:
    find_indels:
        indel_window: 5
        min_count: 2
    subsample:
        min_qual: 20
        method: withoutreplace
        target_coverage: 10
    D:
        min_count: 2
        min_covered_fraction: 0.5
        step_size: 1000
        window_size: 1000
    pi:
        min_count: 2
        min_covered_fraction: 0.5
        step_size: 1000
        window_size: 1000
    theta:
        min_count: 2
        min_covered_fraction: 0.5
        step_size: 1000
        window_size: 1000

popoolation2:
    mpileup2sync:
        min_qual: 20
        memory_gb: 2
    find_indels:
        indel_window: 5
        min_count: 20
    subsample:
        target_coverage: 10
        max_coverage: 10000
        method: withoutreplace
    fst_sliding:
        window_size: 1
        step_size: 1
        min_covered_fraction: 1.0
        min_count: 3
